'use strict';
const $=id=>document.getElementById(id);
const ALPH='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const ROLE={doctor:['医師','innocent','夜に1人を通常攻撃から守る'],mad:['錯乱者','innocent','能力があると思い込むが実際には効果がない'],police:['警官','innocent','夜に1人の行動を止める'],lookout:['見張り','innocent','対象の家を監視する'],investigator:['調査員','innocent','対象の役職情報を調査する'],trapper:['罠師','innocent','対象の家へ罠を置く'],snitch:['密告者','innocent','一度だけ対象の役職を公開する'],provoker:['挑発者','innocent','一度だけ対象へ追加票を与える'],tracker:['追跡者','innocent','対象の夜の行動を追跡する'],cleaner:['清掃屋','impostor','死亡者の役職情報を隠す'],blamer:['濡れ衣師','impostor','対象を反逆陣営に見せかける'],survivor:['生存者','neutral','3回まで自分を守る'],serial:['連続殺人犯','neutral','夜に1人を襲う'],bomber:['爆弾魔','neutral','対象へ爆弾を仕掛ける'],thief:['怪盗','neutral','対象を襲い役職を奪う'],haunter:['亡霊','neutral','対象へ印を付ける'],sorcerer:['魔術師','neutral','役職を予言して攻撃する']};
const PHASE={lobby:'参加者を待っています',mayor:'町長選挙',night:'夜が訪れました',dawn:'夜明け',discussion:'議論の時間',vote:'追放投票',end:'ゲーム終了'};
const App={client:null,snapshot:null,code:null,secret:null,channel:null,poll:null,heart:null,tick:null,busy:false,lastAdvance:0};
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),2400)}
function random(n){const a=new Uint32Array(n);crypto.getRandomValues(a);return [...a].map(v=>ALPH[v%ALPH.length]).join('')}
function parseInvite(v){v=(v||'').trim();if(v.includes('#'))v=v.split('#').pop();const dot=v.indexOf('.');return dot>0?{code:v.slice(0,dot).toUpperCase(),secret:v.slice(dot+1)}:null}
function inviteUrl(){return location.origin+location.pathname+'#'+App.code+'.'+App.secret}
function humanError(e){const m=e?.message||String(e);const map={ROOM_CODE_COLLISION:'コードが重複しました',INVALID_INVITE:'招待URLが正しくありません',ROOM_FULL:'部屋は満員です',GAME_ALREADY_STARTED:'ゲームは開始済みです',PLAYER_COUNT_4_TO_12:'4〜12人で開始してください',NOT_ALL_READY:'準備できていないプレイヤーがいます',HOST_ONLY:'作成者だけが開始できます',VOTE_CLOSED:'現在は投票できません',ACTION_CLOSED:'現在は夜行動を選べません'};for(const k in map)if(m.includes(k))return map[k];return m}
function setBusy(v){App.busy=v;['createBtn','joinBtn'].forEach(id=>$(id).disabled=v)}
async function ensureAuth(){const {data}=await App.client.auth.getSession();if(data.session)return;const {error}=await App.client.auth.signInAnonymously();if(error)throw error}
async function rpc(name,args={}){const {data,error}=await App.client.rpc(name,args);if(error)throw error;return data}
async function init(){const c=window.VEIL_CONFIG||{};if(!c.supabaseUrl||!c.supabaseAnonKey||c.supabaseUrl.includes('PASTE_')||c.supabaseAnonKey.includes('PASTE_')){$('setupError').classList.remove('hidden');$('createBtn').disabled=true;$('joinBtn').disabled=true;return}try{App.client=window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey);await ensureAuth();$('netBadge').textContent='認証済み';$('netBadge').classList.add('on');const saved=JSON.parse(localStorage.getItem('veil_v2_session')||'null');if(saved?.code&&saved?.secret){$('resumeBtn').classList.remove('hidden');$('resumeBtn').onclick=()=>enter(saved.code,saved.secret,true)}const fromHash=parseInvite(location.hash.slice(1));if(fromHash)$('inviteInput').value=location.href}catch(e){$('setupError').classList.remove('hidden');$('setupError').innerHTML='<h2>Supabaseへ接続できません</h2><p>'+humanError(e)+'</p>'}}
async function createRoom(){const name=$('nameInput').value.trim();if(!name)return toast('表示名を入力してください');setBusy(true);try{await ensureAuth();for(let i=0;i<5;i++){const code=random(6),secret=random(32);try{const snap=await rpc('create_room',{p_code:code,p_invite_secret:secret,p_display_name:name});App.code=code;App.secret=secret;App.snapshot=snap;saveSession();await openGame();return}catch(e){if(!String(e.message).includes('ROOM_CODE_COLLISION'))throw e}}throw new Error('部屋コードを作成できませんでした')}catch(e){toast(humanError(e))}finally{setBusy(false)}}
async function joinRoom(){const name=$('nameInput').value.trim();const inv=parseInvite($('inviteInput').value||location.hash.slice(1));if(!name)return toast('表示名を入力してください');if(!inv)return toast('招待URLを確認してください');setBusy(true);try{await ensureAuth();const snap=await rpc('join_room',{p_code:inv.code,p_invite_secret:inv.secret,p_display_name:name});App.code=inv.code;App.secret=inv.secret;App.snapshot=snap;saveSession();await openGame()}catch(e){toast(humanError(e))}finally{setBusy(false)}}
async function enter(code,secret,resume=false){setBusy(true);try{App.code=code;App.secret=secret;App.snapshot=await rpc('room_snapshot',{p_room_code:code});saveSession();await openGame();if(resume)toast('前回の部屋へ復帰しました')}catch(e){localStorage.removeItem('veil_v2_session');toast(humanError(e))}finally{setBusy(false)}}
function saveSession(){localStorage.setItem('veil_v2_session',JSON.stringify({code:App.code,secret:App.secret}))}
async function openGame(){$('home').classList.add('hidden');$('game').classList.remove('hidden');$('roomCode').textContent=App.code;$('netBadge').textContent='同期中';render();subscribe();clearInterval(App.poll);clearInterval(App.heart);clearInterval(App.tick);App.poll=setInterval(refresh,3000);App.heart=setInterval(()=>rpc('heartbeat',{p_room_code:App.code}).catch(()=>{}),15000);App.tick=setInterval(tick,1000);await refresh();}
function subscribe(){if(App.channel)App.client.removeChannel(App.channel);const rid=App.snapshot.room.id;App.channel=App.client.channel('veil-v2-'+rid).on('postgres_changes',{event:'*',schema:'public',table:'rooms',filter:'id=eq.'+rid},refreshSoon).on('postgres_changes',{event:'*',schema:'public',table:'players',filter:'room_id=eq.'+rid},refreshSoon).on('postgres_changes',{event:'*',schema:'public',table:'game_events',filter:'room_id=eq.'+rid},refreshSoon).on('postgres_changes',{event:'*',schema:'public',table:'player_secrets',filter:'room_id=eq.'+rid},refreshSoon).subscribe(status=>{$('netBadge').textContent=status==='SUBSCRIBED'?'同期済み':'再接続中';$('netBadge').classList.toggle('on',status==='SUBSCRIBED')})}
let refreshTimer;function refreshSoon(){clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,120)}
async function refresh(){if(!App.code||App.busy)return;try{App.snapshot=await rpc('room_snapshot',{p_room_code:App.code});render();$('systemText').textContent='DB version '+App.snapshot.room.version+' · 最終同期 '+new Date().toLocaleTimeString()}catch(e){$('netBadge').textContent='再接続中';$('netBadge').classList.remove('on')}}
async function tick(){const r=App.snapshot?.room;if(!r)return;renderTimer();if(!r.phase_ends_at||['lobby','end'].includes(r.phase))return;const due=new Date(r.phase_ends_at).getTime()<=Date.now();if(due&&Date.now()-App.lastAdvance>1800){App.lastAdvance=Date.now();try{App.snapshot=await rpc('advance_phase',{p_room_code:App.code});render()}catch(e){}}}
function render(){const s=App.snapshot;if(!s)return;const r=s.room,players=s.players||[],me=players.find(p=>p.id===s.me?.player_id);$('roomCode').textContent=r.code;$('dayLabel').textContent=r.phase==='lobby'?'LOBBY':r.phase==='end'?'GAME OVER':'DAY '+r.day_no+' · '+r.phase.toUpperCase();$('phaseTitle').textContent=r.phase==='end'?(r.winner+'の勝利'):PHASE[r.phase];renderTimer();$('players').innerHTML=players.map(p=>`<div class="player ${p.alive?'':'dead'}"><i class="dot ${p.online?'online':''}"></i><span class="name">${escapeHtml(p.name)}${p.id===s.me?.player_id?'（自分）':''}</span>${p.id===r.mayor_player_id?'<span class="badge">町長</span>':''}${r.phase==='lobby'?`<span class="badge">${p.ready?'準備OK':'待機'}</span>`:p.revealed_role?`<span class="badge">${escapeHtml(roleName(p.revealed_role))}</span>`:''}</div>`).join('');$('events').innerHTML=(s.events||[]).map(e=>`<div class="event">${escapeHtml(e.message)}</div>`).join('');$('lobbyButtons').classList.toggle('hidden',r.phase!=='lobby');$('startBtn').classList.toggle('hidden',!s.me?.is_host);$('readyBtn').textContent=me?.ready?'準備を取り消す':'準備OK';renderStage(me)}
function renderTimer(){const end=App.snapshot?.room?.phase_ends_at;$('timer').textContent=end?Math.max(0,Math.ceil((new Date(end).getTime()-Date.now())/1000)):'--'}
function roleName(k){return ROLE[k]?.[0]||k||'不明'}
function roleCard(){const s=App.snapshot?.secret;if(!s)return'<div class="notice">役職情報を待っています。</div>';const meta=ROLE[s.role]||[s.role,s.faction,''];return`<div class="role-card ${s.faction}"><div class="eyebrow">${s.faction.toUpperCase()}</div><h3>${escapeHtml(meta[0])}</h3><p>${escapeHtml(meta[2])}</p>${s.uses<99?`<span class="badge">残り ${s.uses} 回</span>`:''}</div>`}
function renderStage(me){const r=App.snapshot.room,body=$('stageBody');if(r.phase==='lobby'){body.innerHTML='<p>全員が準備できたら開始できます。再読み込み・再接続しても同じプレイヤーとして復帰します。</p><div class="notice">招待URLを参加者へ共有してください。</div>';return}if(!me?.alive){body.innerHTML=roleCard()+'<div class="notice">脱落しました。ゲーム終了まで観戦できます。</div>';return}if(r.phase==='end'){body.innerHTML=`<div class="role-card"><div class="eyebrow">RESULT</div><h3>${escapeHtml(r.winner)}の勝利</h3></div>`;return}if(r.phase==='night'){body.innerHTML=roleCard()+'<h3>今夜の行動</h3>'+targetHtml();bindTargets('action');return}if(['mayor','vote'].includes(r.phase)){body.innerHTML='<p>'+(r.phase==='mayor'?'町長に選ぶ人物':'追放する人物')+'を選んでください。</p>'+targetHtml();bindTargets('vote');return}if(r.phase==='dawn'){body.innerHTML='<div class="notice">夜の結果を確認しています。</div>'+roleCard();return}body.innerHTML=roleCard()+'<h3>議論してください</h3><p>情報を整理し、投票に備えてください。</p>'}
function targetHtml(){const me=App.snapshot.me.player_id;return'<div class="targets">'+App.snapshot.players.filter(p=>p.alive&&p.id!==me).map(p=>`<button class="target" data-id="${p.id}">${escapeHtml(p.name)}</button>`).join('')+'</div>'}
function bindTargets(type){document.querySelectorAll('.target').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.target').forEach(x=>x.classList.toggle('selected',x===b));try{if(type==='vote'){App.snapshot=await rpc('submit_vote',{p_room_code:App.code,p_target_player_id:b.dataset.id});toast('投票を保存しました')}else{const sec=App.snapshot.secret||{};const mode=sec.faction==='impostor'?'factionKill':'use';App.snapshot=await rpc('submit_action',{p_room_code:App.code,p_action:{target:b.dataset.id,mode}});toast('夜行動を保存しました')}render()}catch(e){toast(humanError(e))}})}
async function toggleReady(){const me=App.snapshot.players.find(p=>p.id===App.snapshot.me.player_id);try{App.snapshot=await rpc('set_ready',{p_room_code:App.code,p_ready:!me.ready});render()}catch(e){toast(humanError(e))}}
async function startGame(){try{App.snapshot=await rpc('start_game',{p_room_code:App.code});render()}catch(e){toast(humanError(e))}}
async function leave(){try{await rpc('leave_room',{p_room_code:App.code})}catch(e){}localStorage.removeItem('veil_v2_session');location.hash='';location.reload()}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('createBtn').onclick=createRoom;$('joinBtn').onclick=joinRoom;$('readyBtn').onclick=toggleReady;$('startBtn').onclick=startGame;$('copyInviteBtn').onclick=async()=>{await navigator.clipboard.writeText(inviteUrl());toast('招待URLをコピーしました')};$('leaveBtn').onclick=leave;
window.addEventListener('beforeunload',()=>{if(App.code)navigator.sendBeacon?.('')});
init();
